### ISSUE TITLE
need to install libprotoc-dev to build the frontend container

### ISSUE THREAD

**Issue by toby-1-kenobi** [salrashid123/grpc_web_with_gke#1]
When I tried to build the frontend container it failed when trying to install the grpc-web plugin due to missing files.

I was able to fix this by adding this line to the Dockerfile directly after the FROM line
`RUN apt-get update && apt-get install -y libprotoc-dev`

**Comment by salrashid123** [comment]
thanks for reporting; i guess there was a change in the base grpc-web image.

anyway, i added it in here:  https://github.com/salrashid123/grpc_web_with_gke/commit/4f2ef19dd7b1464c0349e814be4fec5ac9e6da16

and pushed the docker image too
